# Generated by Django 5.1.4 on 2025-01-29 12:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_remove_review_body_review_description_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='description',
            new_name='comment',
        ),
    ]
