# Generated by Django 5.1.4 on 2025-01-29 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_rename_description_review_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='title',
            field=models.CharField(max_length=128, unique=True),
        ),
    ]
